### PR TITLE
Fill FileBuffer before checking `eof`

### LINKED ISSUE #126: Using `read(::FileBuffer, nb)` returns no data on first read
```julia
julia> using FilePathsBase

julia> write("test.txt", "testing")
7

julia> io = FilePathsBase.FileBuffer(Path("test.txt"))
FileBuffer(p"test.txt", IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1), true, false, false)

julia> read(io, 3)
UInt8[]

julia> read(io, 3)
UInt8[]

julia> read(io, UInt8)
0x74

julia> read(io, 3)
3-element Vector{UInt8}:
 0x65
 0x73
 0x74
```

### LINKED ISSUE #134: `eof(::FileBuffer)` incorrectly returns `true` before filling the buffer
According to the `eof` docs:

> If the stream is not yet exhausted, this function will block to wait for more data if necessary, and then return `false`.

The current behaviour of always returning `true` before the first read means that the `write(A::IO, B::IO)` method (for `B<:FileBuffer`) and similar patterns are currently broken. 

This is currently causing a problem for [CSV.jl](https://github.com/JuliaData/CSV.jl/pull/892#issuecomment-917037294) with `S3Path` and is also causing https://github.com/rofinn/FilePathsBase.jl/issues/126.

### PR DESCRIPTION
**Pull request by nickrobinson251**
- closes #134 
- edit: closes #126 too

### CODE REVIEW

File: test/buffer.jl [hunk 1]
```diff
@@ -7,7 +7,7 @@ using FilePathsBase: FileBuffer
         try
             @test isreadable(io)
             @test !iswritable(io)
-            @test eof(io)
+            @test !eof(io)
```
Comment (nickrobinson251) [inline test/buffer.jl:10]: i think this was just a mistake in the tests

File: test/buffer.jl [hunk 2]
```diff
@@ -44,9 +44,10 @@ using FilePathsBase: FileBuffer
                 try
                     @test isreadable(io)
                     @test iswritable(io)
-                    @test eof(io)
+                    @test !eof(io)
```
Comment (nickrobinson251) [inline test/buffer.jl:47]: likewise, this i think was also a mistake in the tests

File: test/buffer.jl [hunk 3]
```diff
@@ -83,6 +84,21 @@ using FilePathsBase: FileBuffer
         end
     end
 
+    @testset "eof" begin
+        mktempdir(SystemPath) do d
+            p, _ = mktemp(d)
+            io = FileBuffer(p; write=true)
+            @test eof(io)
```
Comment (nickrobinson251) [inline test/buffer.jl:91]: i'm not sure if this new testset is worth it, but we didn't have a test for `eof` when passed an empty file, so i though i'd add that, and to be explicit about what (i think) the expected interaction is with read and write

File: test/buffer.jl [hunk 4]
```diff
@@ -83,6 +84,21 @@ using FilePathsBase: FileBuffer
         end
     end
 
+    @testset "eof" begin
+        mktempdir(SystemPath) do d
+            p, _ = mktemp(d)
```
Comment (nickrobinson251) [inline test/buffer.jl:89]: i use `mktempdir` to create a parent dir to pass to `mktemp`, because there's no `mktemp(func, SystemPath)` method so couldn't just use `mktemp(SystemPath) do ...`

**Comment by omus** [comment]
@nickrobinson251 I'm pretty sure this will also solve https://github.com/rofinn/FilePathsBase.jl/issues/126. You may want to add a test for that to check.

**Review by omus — APPROVED** [review]
LGTM

File: test/buffer.jl (hunk 4 above)
Comment (nickrobinson251) [reply test/buffer.jl]: ooo, turns out i was wrong! I was writing `mktemp(SystemPath) do (p, io)` where i needed `mktemp(SystemPath) do p, io` (without the brackets) :D

File: src/buffer.jl [hunk 5]
```diff
@@ -38,7 +38,13 @@ Base.seek(buffer::FileBuffer, n::Integer) = seek(buffer.io, n)
 Base.seekstart(buffer::FileBuffer) = seekstart(buffer.io)
 Base.seekend(buffer::FileBuffer) = seekend(buffer.io)
 Base.position(buffer::FileBuffer) = position(buffer.io)
-Base.eof(buffer::FileBuffer) = eof(buffer.io)
+function Base.eof(buffer::FileBuffer)
```
Comment (rofinn) [inline src/buffer.jl:41]: I guess the reason pre-emptively reading the file before calling `eof` is fine is because our `_read` function checks the size of the `io` first... so this should only happen once?

**Review by rofinn — APPROVED** [review]
LGTM, just added a clarification question about the default `_read` behaviour. I'll merge and tag tomorrow if there are no other comments.

File: src/buffer.jl (hunk 5 above)
Comment (nickrobinson251) [reply src/buffer.jl:41]: yes, that's my understanding
