### PR TITLE
Change parents to not error when no parents are found

### LINKED ISSUE #19: make `parent(p"file.txt")` return `p"."` ?
Currently it errors.

```
julia> parent(p"file.txt")
ERROR: file.txt has no parents
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] parents at /Users/oxinabox/.julia/packages/FilePathsBase/AeOcX/src/path.jl:143 [inlined]
 [3] parent(::PosixPath) at /Users/oxinabox/.julia/packages/FilePathsBase/AeOcX/src/path.jl:120
 [4] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by rofinn**
This seems to match what pathlib does now. Closes #19

### CODE REVIEW

File: src/path.jl [hunk 1]
```diff
@@ -121,23 +121,31 @@ Base.parent(fp::AbstractPath) = parents(fp)[end]
...
+1-element Array{PosixPath,1}:
+ p"."
+ ```
 """
 function parents(fp::T) where {T <: AbstractPath}
     if hasparent(fp)
         return [Path(fp, fp.segments[1:i]) for i in 1:length(fp.segments)-1]
     else
-        error("$fp has no parents")
+        return [isempty(fp.root) ? Path(fp, tuple(".")) : Path(fp, ())]
```
Comment (oxinabox) [inline src/path.jl]: If possible, can we make it so that the result of 

```
parents(x) === x
```
for this case?

Comment (rofinn) [reply src/path.jl]: Just so we aren't allocating?

Comment (oxinabox) [reply src/path.jl]: Because in similar cases (e.g. array parents)
I do
`isroot(x) = parent(x)===x

Comment (rofinn) [reply src/path.jl]: Hmmm, I think that's a bit weird, but sure. I'll note that your `isroot` method is wrong because it would return true for even non-root relative paths (e.g., `isroot(p".")` should probably return false).
